name: "SEMVER parser"
description: "Parses hashtag semver from git commit messages (#minor, #major and #patch)"
author: "Tom Brouwer"
outputs:
  semver:
    description: "The semver update key (eg: minor, major or patch)"
inputs:
  default_semver:
    description: "The default semver update key."
    required: false

runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "truck"
  color: "green"
